excluded dev env main- added update tfvars step sub - commented commit step sub

diff --git a/.github/workflows/apigw-automation-sub.yaml b/.github/workflows/apigw-automation-sub.yaml
--- a/.github/workflows/apigw-automation-sub.yaml
+++ b/.github/workflows/apigw-automation-sub.yaml
@@ -30,7 +30,7 @@ jobs:
       - name: Print environment
         run: |
           echo "Triggered for environment: ${{ inputs.environment }}"
-  
+
       - name: Checkout current repository
         uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
         with:
@@ -60,13 +60,13 @@ jobs:
         run: |
           BOT_USER="github-actions[bot]"
           BOT_ENC=$(printf '%s' "$BOT_USER" | jq -sRr @uri)
-          
+
           BOT_ID=$(curl -s \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github+json" \
             https://api.github.com/users/$BOT_ENC \
             | jq -r .id)
-          
+
           BOT_EMAIL="${BOT_ID}+${BOT_USER}@users.noreply.github.com
 
           echo "BOT_EMAIL=${BOT_EMAIL}" >> $GITHUB_OUTPUT
@@ -84,10 +84,10 @@ jobs:
 
           echo "env_label=${label1}" >> $GITHUB_OUTPUT
           echo "prnum_label=${label2}" >> $GITHUB_OUTPUT
-      
+
       - name: List open PRs
         id: get_open_prs
-        env: 
+        env:
           INTEROP_INFRA_REPO_TOKEN: ${{ secrets.INTEROP_INFRA_REPO_TOKEN }}
         run: |
           set -euo pipefail
@@ -99,17 +99,17 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ vars.INTEROP_INFRA_REPO }}/pulls?state=open)
 
-          
-          # find matching prs based on provided labels 
+
+          # find matching prs based on provided labels
           label1="${{ steps.build_labels.outputs.env_label }}"
           label2="${{ steps.build_labels.outputs.prnum_label }}"
 
           MATCHING_PRS=$(echo $OPEN_PRS | jq --arg label_env "${label1}" --arg label_pr "${label2}" \
               '.[] | select(
-                (.labels   | any(.name == $label_env)) and 
+                (.labels   | any(.name == $label_env)) and
                 (.labels   | any(.name == $label_pr))
               )')
-          
+
           if [[ -n "$MATCHING_PRS" ]]; then
             echo "MATCHING PRs"
             echo $MATCHING_PRS
@@ -117,76 +117,174 @@ jobs:
           else
             echo "No matching PRs, will create a new one"
             echo "create_pr=true" >> $GITHUB_OUTPUT
-          fi                  
-
-      - name: Commit changes to target repo
-        id: commit_changes
+          fi
+      # DEBUG TO REMOVE
+      - name: Print changed services for this environment
         run: |
-          BOT_EMAIL=${{ steps.bot_creds.outputs.BOT_EMAIL }}
-          BOT_USER=${{ steps.bot_creds.outputs.BOT_USER }}
+          echo "Changes file path: ${{ inputs.changes_file_path }}"
+          if [ -f "${{ inputs.changes_file_path }}" ]; then
+            echo "=== Changes for environment: ${{ inputs.environment }} ==="
+            cat "${{ inputs.changes_file_path }}"
+          else
+            echo "No changes file found for env ${{ inputs.environment }}."
+          fi
 
-          cd interop-infra
-
-          TARGET_BRANCH_FULL=${{ vars.INTEROP_INFRA_TARGET_BRANCH }}-$PR_NUMBER-$ENVIRONMENT
-          git checkout -b $TARGET_BRANCH_FULL
-          git pull origin $TARGET_BRANCH_FULL || true
-          
-          git config user.name "$BOT_USER"
-          git config user.email "$BOT_EMAIL"
-          
-          # TODO
-          touch test-file.txt
-          echo "This is a test file ${{ github.run_id }}" >> test-file.txt
-          git add test-file.txt
-          git commit -m "chore: test file for PR opener ${{ github.run_id }}"
-
-          git push --set-upstream origin $TARGET_BRANCH_FULL
-
-      - name: Open PR for environment ${{ inputs.environment }}
-        id: open_pr
-        if: ${{ steps.get_open_prs.outputs.create_pr == true }}
-        env: 
-          INTEROP_INFRA_REPO_TOKEN: ${{ secrets.INTEROP_INFRA_REPO_TOKEN }}
+      - name: Update tfvars
         run: |
-            #TODO
-            PR_OPEN_RES=$(curl -sSL \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer $INTEROP_INFRA_REPO_TOKEN" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ vars.INTEROP_INFRA_REPO }}/pulls \
-            -d '{"title":"['"$ENVIRONMENT"'] TBD Automated update from Repo PR Opener","head":"'${{ vars.INTEROP_INFRA_TARGET_BRANCH }}-$PR_NUMBER-$ENVIRONMENT'","base":"main","body":"TODO This is an example"}')
+          set -euo pipefail
 
-            CURL_STATUS=$(echo $PR_OPEN_RES | jq -r '.status')
-            CURL_ERRORS=$(echo $PR_OPEN_RES | jq -r '.errors//""')
+          CHANGES_FILE="${{ inputs.changes_file_path }}"
+          ENV="${{ inputs.environment }}"
 
-            if [[ "$CURL_STATUS" == "404" ]] || [[ -n "$CURL_ERRORS" ]]; then
-                echo "Failed to create PR: $PR_OPEN_RES"
-                exit 1
-            else
-                echo "PR created successfully $PR_OPEN_RES"
+          # TODO: da modificare per adattarlo al repo corretto
+          # src/main/core-es1/env/${ENV}/terraform.tfvars
+          TFVARS_FILE="src/main/core-es1/env/${ENV}/terraform.tfvars"
+
+          # Se il file non esiste, esci senza errore
+          if [ ! -f "$TFVARS_FILE" ]; then
+            echo "File $TFVARS_FILE not found."
+            exit 0
+          fi
+
+          # associazione servizio -> variabile da aggiornare
+          declare -A service_to_var
+          service_to_var=(
+            ["api-gateway"]="api_gateway_raw_url"
+            ["authorization-server-node"]="authorization_server_node_raw_url"
+            ["backend-for-frontend"]="backend_for_frontend_raw_url"
+            ["m2m-gateway"]="m2m_gateway_raw_url"
+          )
+          # associazione servizio -> nome file openapi
+          declare -A service_to_file
+          service_to_file=(
+            ["api-gateway"]="apiGatewayApi.yml"
+            ["authorization-server-node"]="authorizationServerApi.yml"
+            ["backend-for-frontend"]="bffApi.yml"
+            ["m2m-gateway"]="m2mGatewayApi.yml"
+          )
+
+          # debug
+          echo "*** tfvars PRIMA ***"
+          cat "$TFVARS_FILE"
+          echo "********************"
+
+           # ciclo i servizi cambiati nel file
+          for svc in $(yq 'keys | .[]' "$CHANGES_FILE"); do
+
+            # popolo il nuovo tag per il servizio se non esiste vado avanti
+            new_tag=$(yq ".\"$svc\".after" "$CHANGES_FILE")
+            if [[ "$new_tag" == "null" ]]; then
+              continue
             fi
 
-            # Pull requests are a type of issue. Any actions that are available in both pull requests and issues, like managing assignees,
-            # labels, and milestones, are handled by the REST API to manage issues. 
-            # To perform these actions on pull requests, you must use the issues API endpoints (for example, /repos/{owner}/{repo}/issues/{issue_number}), 
-            # not the pull requests endpoints. For more information, see REST API endpoints for issues.
+            # popolo la variabile corrispondente al servizio se non esiste vado avanti
+            var_name="${service_to_var[$svc]}"
+            if [ -z "$var_name" ]; then
+              continue
+            fi
 
-            PR_NUMBER=$(echo $PR_OPEN_RES | jq -r '.number' )
-            echo "Target PR Number: $PR_NUMBER"
-            
-            label1="${{ steps.build_labels.outputs.env_label }}"
-            label2="${{ steps.build_labels.outputs.prnum_label }}"
-            
-            echo "Applying labels: $label1, $label2"
-            LABELING_RESULT=$(curl -sSL \
-              -X PUT \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer $INTEROP_INFRA_REPO_TOKEN" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              https://api.github.com/repos/${{ vars.INTEROP_INFRA_REPO }}/issues/$PR_NUMBER/labels \
-              -d "{\"labels\": [ \"$label1\", \"$label2\" ] }")
+            # popolo il nome del file openapi
+            openapi_file="${service_to_file[$svc]}"
+            if [ -z "$openapi_file" ]; then
+              continue
+            fi
 
-            echo "Labels applied:"
-            echo "$LABELING_RESULT"
+              # modificare branch/tag in base alle casistiche; ragionare per tag
+            #
+            if [[ "$new_tag" == "develop" ]]; then
+              ref="refs/heads/develop"
+            else
+              ref="refs/tags/${new_tag}"
+            fi
 
+            #  passo new_tag al nuovo valore della url raw
+            url_raw="https://raw.githubusercontent.com/pagopa/interop-be-monorepo/$ref/packages/api-clients/open-api/$openapi_file"
+
+            #  se la variabile è già presente la aggiorno
+
+            # TODO rivedere formattazione/spazi - in questo modo considero anche spazi/tab tra nome variabile e uguale
+            if grep -q "^$var_name[[:space:]]*=" "$TFVARS_FILE"; then
+              sed -i -E "s|^$var_name[[:space:]]*=.*|$var_name = \"$url_raw\"|g" "$TFVARS_FILE"
+              echo "$var_name updated"
+            else
+              # aggiungo la variabile se non trovata; aggiungo alla fine
+              echo "" >> "$TFVARS_FILE"
+              echo "$var_name = \"$url_raw\"" >> "$TFVARS_FILE"
+              echo "$var_name added"
+            fi
+          done
+
+          # debug
+          echo "=== File tfvars DOPO ==="
+          cat "$TFVARS_FILE"
+
+      # - name: Commit changes to target repo
+      #   id: commit_changes
+      #   run: |
+      #     BOT_EMAIL=${{ steps.bot_creds.outputs.BOT_EMAIL }}
+      #     BOT_USER=${{ steps.bot_creds.outputs.BOT_USER }}
+
+      #     cd interop-infra
+
+      #     TARGET_BRANCH_FULL=${{ vars.INTEROP_INFRA_TARGET_BRANCH }}-$PR_NUMBER-$ENVIRONMENT
+      #     git checkout -b $TARGET_BRANCH_FULL
+      #     git pull origin $TARGET_BRANCH_FULL || true
+
+      #     git config user.name "$BOT_USER"
+      #     git config user.email "$BOT_EMAIL"
+
+      #     TODO: da modificare
+      #     REL_TFVARS_FILE="core-es1/env/${ENV}/terraform.tfvars"
+      #     git add "$REL_TFVARS_FILE"
+
+      #     git commit -m "chore: test file for PR opener ${{ github.run_id }}"
+
+      #     git push --set-upstream origin $TARGET_BRANCH_FULL
+
+      # - name: Open PR for environment ${{ inputs.environment }}
+      #   id: open_pr
+      #   if: ${{ steps.get_open_prs.outputs.create_pr == true }}
+      #   env:
+      #     INTEROP_INFRA_REPO_TOKEN: ${{ secrets.INTEROP_INFRA_REPO_TOKEN }}
+      #   run: |
+      #       #TODO
+      #       PR_OPEN_RES=$(curl -sSL \
+      #       -X POST \
+      #       -H "Accept: application/vnd.github+json" \
+      #       -H "Authorization: Bearer $INTEROP_INFRA_REPO_TOKEN" \
+      #       -H "X-GitHub-Api-Version: 2022-11-28" \
+      #       https://api.github.com/repos/${{ vars.INTEROP_INFRA_REPO }}/pulls \
+      #       -d '{"title":"['"$ENVIRONMENT"'] TBD Automated update from Repo PR Opener","head":"'${{ vars.INTEROP_INFRA_TARGET_BRANCH }}-$PR_NUMBER-$ENVIRONMENT'","base":"main","body":"TODO This is an example"}')
+
+      #       CURL_STATUS=$(echo $PR_OPEN_RES | jq -r '.status')
+      #       CURL_ERRORS=$(echo $PR_OPEN_RES | jq -r '.errors//""')
+
+      #       if [[ "$CURL_STATUS" == "404" ]] || [[ -n "$CURL_ERRORS" ]]; then
+      #           echo "Failed to create PR: $PR_OPEN_RES"
+      #           exit 1
+      #       else
+      #           echo "PR created successfully $PR_OPEN_RES"
+      #       fi
+
+      #       # Pull requests are a type of issue. Any actions that are available in both pull requests and issues, like managing assignees,
+      #       # labels, and milestones, are handled by the REST API to manage issues.
+      #       # To perform these actions on pull requests, you must use the issues API endpoints (for example, /repos/{owner}/{repo}/issues/{issue_number}),
+      #       # not the pull requests endpoints. For more information, see REST API endpoints for issues.
+
+      #       PR_NUMBER=$(echo $PR_OPEN_RES | jq -r '.number' )
+      #       echo "Target PR Number: $PR_NUMBER"
+
+      #       label1="${{ steps.build_labels.outputs.env_label }}"
+      #       label2="${{ steps.build_labels.outputs.prnum_label }}"
+
+      #       echo "Applying labels: $label1, $label2"
+      #       LABELING_RESULT=$(curl -sSL \
+      #         -X PUT \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer $INTEROP_INFRA_REPO_TOKEN" \
+      #         -H "X-GitHub-Api-Version: 2022-11-28" \
+      #         https://api.github.com/repos/${{ vars.INTEROP_INFRA_REPO }}/issues/$PR_NUMBER/labels \
+      #         -d "{\"labels\": [ \"$label1\", \"$label2\" ] }")
+
+      #       echo "Labels applied:"
+      #       echo "$LABELING_RESULT"
